### ISSUE TITLE
Cut up whitepapers to build up with includes

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/info_tftech#21]
from
https://drive.google.com/drive/folders/1dBYN1k6Hp0VEaqOdcT2XEFqyF0ScQROc

to:
https://github.com/threefoldtech/info_tftech/tree/development/docs/whitepapers

- 1 folder per whitepaper
- make different sections in different parts so they can be reused
- use include macro's in the overview doc

**Comment by despiegk** [comment]
need this for block.one as well
work with Kristof on this one as well, let him know when progress can be made

**Comment by VonSub** [comment]
They are there now, but still need to be cut up into different pieces for reusing. will do this post-event.

**Comment by VonSub** [comment]
for the larger ones this is all done. for the smaller ones includes don't make a whole lot of sense. closing.
